#配置druid数据源
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8
      username: root
      password: 15193651772Aa!

  #开发环境下，关闭缓存，生产环境下，打开缓存
  thymeleaf:
    cache: false
  web:
    resources:
      static-locations: classpath:static
  servlet:
    multipart:
      max-file-size: 104857600
#配置mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
savePath: c:/uploadtest