sysUser: 张三
age: 20

com:
  xzit:
    model:
      users:
        name: 李四
        gender: 男
        age: 22
        money: 234.99
        birth: 1999/8/3
        likes:
          - 打球
          - 游泳
          - 游戏
        list: [ aa,bb,cc ]
        set: [xxx,yyy,zzz]
        map:
          k1: v1
          k2: v2
        map1: { k1: v1,k2: v2,k3: v3 }
        stuList:
          - name: 学生1
            age: 20
          - name: 学生2
            age: 19
        stuList1:
          - { name: 学生3,age: 22 }
          - { name: 学生4,age: 25 }